package enums;

public enum EEvent {

	THE_CALM_BEFORE_THE_STORM, ENGINEERING_CORPS, TWEE_GEBROEDERS_PLUGS_BREACH, DELTA_PLAN,
	NEW_PORT, HOOGHEEMRAADSCHAPPEN, EMERGENCY_MEETING, MAIL_EXCHANGE, EMERGENCY_SANDBAGS,
	THE_LITTLE_DUTCH_BOY, WATER_MANAGEMENT, STOOMGEMAAL_VIER_NOORDER_KOGGEN, ZUIDERZEEVEREENIGING,
	STORMVLOEDSEINDIENST

}
