package enums;

public enum ELayerZ {

	VISIBILITY_FALSE, BACKGROUND, MAP, SEA_LEVEL_MARKER, HYDRAULIC_STRUCTURE, CARDS_ROLE, CARDS,
	SELECT_IMAGEVIEW, ACTION_INDICATORS, MAP_PAWNS, MAP_BUILDINGS, MAP_CUBES, DEFAULT, ICONS_MISC;

}
