package enums;

public enum ELayerZ {

	VISIBILITY_FALSE, BACKGROUND, MAP, POPULATION_LOSS, SEA_LEVEL_MARKER, HYDRAULIC_STRUCTURE,
	CIRCLES, CARDS_ROLE, CARDS, SELECT_IMAGEVIEW, ACTION_INDICATORS, DIKES, MAP_PAWNS,
	MAP_BUILDINGS, MAP_CUBES, DEFAULT, ICONS_MISC;

}
