package enums;

public enum ETagName {

	NOORDERZIJLVEST, FRYSLAN, NOORDOOSTPOLDER, FLEVOLAND, MARKERWAARD, WIERINGERMEER, KENNEMERLAND,
	DELFLAND, VOORNE_PUTTEN, GOERRE_OVERFLAKKEE, SCHOUWEN_DUIVELAND, WALCHEREN, ZUID_BEVELAND,
	ZEEUWS_VLAANDEREN, WEST_BRABANT, HOEKSE_WAARD, LAND_VAN_ALTENA, LAND_VAN_HEUSDEN,
	LAND_VAN_MAAS_EN_WAAL, PEEL_EN_MAASVALLEI, ROER_EN_OVERMAAS, VOLLENHOVE, IJSSELDELTA,
	RIJN_EN_IJSSEL, BETUWE, VIJFHERELANDEN, KROMME_RIJN, GELDERSE_VALLEI, DRENTHE, TWENTE,
	OOST_BRABANT, NOORDZEE, ZUIDERZEE

}
